baseurl = "/"
title = "Savvy Data Science Blog"
copyright = "&copy; 2019 Savvy"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

#Ignore files 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[Author]
  name = "Savithri Rajaraman  "
  bio = "Data Science Blogger"
  avatar = "img/avatar.png"

[Params]
  subtitle = "Data Science Blog" # Subtitle of your site
  description = "Savvy Blogs" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "project", "RSS", "about", "resources"]
 # menu = [main, side, footer]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[menu]

  [[menu.main]]
    name = "Posts"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/post/"
    weight = -100
    
    
  [[menu.main]]
    name = "Projects"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/Project/"
    weight = -100
    
   [[menu.main]]
    name = "About"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/Aboutme/"
    weight = -100
    
[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
  
[Params.widgets.social]
  # Enable parts of social widget
  twitter = "username"
  linkedin = "username"
  github = "username"
  email = "example@example.com"
